### ISSUE TITLE
Qmllint does not work after updating the extension to 3.0.2

### ISSUE THREAD

**Issue by SnowMB** [seanwu1105/vscode-qt-for-python#257]
Since the update of the extension to 3.0.2 qmllint has stopped working for me. I tested with qmllint version 6.3.0, 6.4.0 and 6.4.1.

I don't use PyQt or PySide, I just use the extension for qml support in my c++ projects. I used the qmllint.exe from the official Qt installer.

I just get this window:

![image](https://user-images.githubusercontent.com/7050959/204805121-105d90d8-caef-4fb4-9ee0-640e9a285460.png)

And this message in the Qt for python log window:

```shell
Could not parse version: 
```

I had to disable qmllint for now.

**Comment by seanwu1105** [comment]
Since the behavior of `qmllint` differs between 6.3.2 and 6.4.1. I have to check the version by using `qmllint --version` first to apply corresponding linting command. The `qmllint` from PySide6 prints `qmllint 6.4.1` on the command line but it seems the `qmllint.exe` from the official Qt installer shows a GUI instead. As this extension is only designed to support PySide6, I think I will keep the current behavior for now. The support for 6.3.2 will be dropped in next major release so this problem should not exist anymore at that time.

**Comment by seanwu1105** [comment]
@SnowMB This release should fix your problem: https://github.com/seanwu1105/vscode-qt-for-python/releases/tag/v4.0.0

You can try it by installing the preview version. Let me know if there is any error.

**Comment by SnowMB** [comment]
Works for me, thank you 👍
